version: '3'
services:
  notebook:
    build:
      context: ./${IMAGE}
      dockerfile: Dockerfile
    image: ${IMAGE}:${TAG:-latest}
    volumes:
      - ${PWD}/home:/home/jovyan
      - ${PWD}/keys:/etc/ssl/notebook
    user: 'root'
    environment:
      RESTARTABLE: 'yes'
      JUPYTER_ENABLE_LAB: 'yes'
      GRANT_SUDO: 'yes'
    ports:
      - ${PORT:-8888}:8888
    command: "start-notebook.sh \
              --NotebookApp.password=${PASSWD} \
              --NotebookApp.certfile=/etc/ssl/notebook/mycert.pem \
              --NotebookApp.keyfile=/etc/ssl/notebook/mykey.key"
